GET http://localhost:5186/games

###
GET http://localhost:5186/games/1

###
POST http://localhost:5186/games
Content-Type: application/json

{
  "name": "Super Mario Bros Wonder",
  "genre": "Platformer",
  "price": 59.99,
  "releaseDate": "2023-10-20"
}